---
title: "Supplementary fig. 2"
author: "Marta Casado-Pelaez"
output:  
  html_document:
    toc: true
    toc_float:
       collapsed: false
       smooth_scroll: false
    fig_caption: true

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', 
                      message = FALSE, warning = FALSE)
```

---

This script generates panels A, C, D and E of supplementary figure 3. 

---


##### **Libraries:**

```{r}
library(Seurat)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(sccomp)
library(here)
```

##### **Load data:**

```{r}
# Seurat objects
dermis <- readRDS(here::here("data", "adult_aged", "dermis.RDS"))
myeloid <- readRDS(here::here("data", "adult_aged", "myeloid.RDS"))
lymphoid <- readRDS(here::here("data", "adult_aged", "lymphoid.RDS"))

# Sccomp object
sccomp_myeloid <- readRDS(here::here("data", "adult_aged", "sccomp_myeloid.RDS"))

# Deepscore predictions
df_deepscore_predicted <- readRDS(here::here("data", "adult_aged", "df_deepscore_predicted.RDS"))
```


\

### **Supplementary figure 3a**

```{r, fig.width = 16, fig.height = 10}
plots <- sccomp::plot_summary(sccomp_myeloid) 

plots$boxplot

# save
file.name <-  here::here("figures", "supp_fig_3a.pdf")
ggsave(file = file.name, width = 15, height = 8)
```

### **Supplementary figure 3c**

```{r, fig.width = 6.5, fig.height = 12}
features <- c("Monocyte_1", "Macrophage_2", "Dendritic cell")

fp_plots <- features %>%
  purrr::imap(~Seurat::VlnPlot(object = dermis, 
                               features = "Il1b", 
                               split.by = "condition", 
                               idents = .x, 
                               cols = c("lightgray", "red")) +
  labs(title = .x) +
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_blank()))

gg <- ggpubr::ggarrange(plotlist = fp_plots, ncol = 1, nrow = 3)
gg

# save
ggsave(gg, file = here::here("figures", paste0("supp_fig_3c.pdf")), 
         width = 16, height = 6)
```

### **Supplementary figure 3d**

```{r, fig.width = 4, fig.height = 8}
load("/Users/mcasado/Documents/Labs/Cellular_systems_genomics/Projects/Aznar_project/Single_cell/aged_adult/transcriptional_noise/data3.Rdata")

matchSCore2::summary_barplot(data$prediction, data$final.annot) + 
    labs(title = "CD45+ Myeloid") +
    theme(plot.title = element_text(size = 15, hjust = 0.5),
          plot.margin = unit(c(0.5,0.5,0.5,2.5), "lines")) +
  scale_fill_manual(name = "", labels = c("Unaffected cells", "Age-affected cells"), values = c("lavender","mediumpurple3")) +
  theme_bw() +
  coord_cartesian(ylim = c(0, 20))+
  ylab("% of cells") +
  xlab("") +
  theme(
    legend.title = element_blank(),
    legend.text = element_text(size = 13),
    axis.text.x = element_text(colour = "black", size = 14, angle = 45, hjust = 1, vjust = 1),
    axis.text.y = element_text(colour = "black", size = 16),
    axis.title.y = element_text(color="black", size=14),
    axis.line = element_line(colour = "black", size = 1),
    panel.grid.major = element_blank(), panel.border = element_blank())
```

### **Supplementary figure 3e**

```{r, fig.width = 6, fig.height = 6}
features <- c("Il17ra", "Il17rc", "Il17a", "Il17f")

Idents(dermis) <- dermis$condition
conditions <- levels(factor(dermis$condition))

dt <- conditions %>%
  purrr::imap(~subset(dermis, idents = .x) %>%
                 SetIdent(., value = "annotation"))

fp_plots <- dt %>%
  purrr::imap(~Seurat::DotPlot(object = .x,
                           features = features,
                           cols = c("lightgray","blue"),
                           col.min = -2.5, 
                           col.max = 2.5,
                           dot.min = 0,
                           dot.scale = 7.5,
                           idents = .x@active.ident,
                           cluster.idents = FALSE,
                           scale = TRUE,
                           scale.by = "radius") + 
  theme(axis.text.x = element_text(angle = 90),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_color_gradient2(low = "#1b13f0", mid = "lightgray", high = "#c7080e") 
  )

gg <- ggpubr::ggarrange(plotlist = fp_plots, ncol = 2, nrow = 1)
gg

# save
ggsave(gg, file = here::here("figures", paste0("supp_fig_3e.pdf")), 
         width = 16, height = 6)
```

